### ISSUE TITLE
NoReverseMatch at /htmx/ Reverse for 'app_Categorytbl_htmx_create' not found.

### ISSUE THREAD

**Issue by dgleba** [mmcardle/django_builder#180]
This issue is similar, but I am not sure if it is the same as https://github.com/mmcardle/django_builder/issues/178. So I create a new issue here.

1.

The [builder](https://djangobuilder.io) created this in  `templates / htmx / htmx.html`:

![image](https://user-images.githubusercontent.com/4622715/226116464-74f00a3e-8fc6-438c-8a46-b0ca3d07165b.png)

To get it to work, I edited it like this:
`blogapp` is the name of my app. I changed `app_` to `blogapp_`. Refer to picture just below.

![image](https://user-images.githubusercontent.com/4622715/226116564-10fb1cab-8436-4c6d-a436-7c8c1c021796.png)

This then matches the path in `urls.py`.
![image](https://user-images.githubusercontent.com/4622715/226117084-6e651d7b-4752-4178-ae71-9f2145fcf835.png)

2.

I also changed `blogapp / htmx.py` .  I added `blog` in front of `app_...`
![image](https://user-images.githubusercontent.com/4622715/226116949-18b69902-f3bb-4282-b61f-c1d5039a0d90.png)

3.
then I got this page.
![image](https://user-images.githubusercontent.com/4622715/226117242-300ec6aa-1ec8-46fa-9b35-efd98325f7ef.png)

4.
Thoughts?

5.
Attached full error message:
[error.htmx.2023-03-17_Fri_22.35-PM.txt](https://github.com/mmcardle/django_builder/files/11008930/error.htmx.2023-03-17_Fri_22.35-PM.txt)

**Comment by mmcardle** [comment]
This issue should now be fixed and deployed to djangobuilder.io

**Comment by dgleba** [comment]
Thanks for the update. 

I see the changes in `htmx.html`.

I still see `app_` in `blogapp / htmx.py`

I haven't tried it yet, but should it be `blogapp_`?

![2023-03-19 09_24_40-Django Builder](https://user-images.githubusercontent.com/4622715/226178536-709f1f49-4543-4c29-a77f-2b66bbb84d1c.png)
