### ISSUE TITLE
There is no way to enter a external foreign key

### ISSUE THREAD

**Issue by groundswel** [mmcardle/django_builder#72]
First of all thank you for this project. 

However one issue I faced is that there is no way to enter a external foreign key from the UI though it gives the hit on how to add it.

**Comment by mmcardle** [comment]
Yup you are correct, thats a bug.
This used to work so think it has regressed.

**Comment by mmcardle** [comment]
This should be fixed now

**Comment by groundswel** [comment]
Cloned the latest version but still the same behaviour. You cannot enter anything in the input field.
